# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CombineReactor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "WeakMapTable", "~> 1.1"

  target 'CombineReactorTests' do
  end
end
